name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install React dependencies
      working-directory: ./frontend
      run: npm install
    
    - name: Run React tests
      working-directory: ./frontend
      run: npm test -- --passWithNoTests
    
    - name: Build React app
      working-directory: ./frontend
      run: npm run build
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install Python dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run Python tests
      working-directory: ./backend
      run: |
        if [ -d tests ]; then python -m unittest discover tests; fi
    
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install React dependencies
      working-directory: ./frontend
      run: npm install
    
    - name: Build React app
      working-directory: ./frontend
      run: npm run build
    
    - name: Copy build files to backend static folder
      run: |
        mkdir -p backend/www
        cp -r frontend/build/* backend/www/
